+ add new extensions lp/perfum/shoes
lamoda/crpt-oms-api-client pull request #10
Opened 2020-10-02 14:03 UTC by XilefNori

2020-10-05 16:43 UTC, akurov-lam approved these changes

2020-10-05 20:00 UTC, HaiD84 requested changes

2020-10-05 20:00 UTC, HaiD84 commented on src/V2/Dto/CreateOrderForEmissionICRequestLp.php
> +use DateTimeInterface;
Ненужный импорт.

2020-10-05 20:00 UTC, HaiD84 commented on src/V2/Dto/CreateOrderForEmissionICRequestLp.php
> +     * CreateOrderForEmissionICRequestLight constructor.
Бесполезный комментарий от другого класса.

2020-10-05 20:00 UTC, HaiD84 commented on src/V2/Dto/CreateOrderForEmissionICRequestPerfum.php
> +use DateTimeInterface;
Тут тоже ненужный импорт и комментарий в конструкторе.

2020-10-05 20:00 UTC, HaiD84 commented on src/V2/Dto/CreateOrderForEmissionICRequestShoes.php
> +use DateTimeInterface;
И тут.

2020-10-05 20:00 UTC, HaiD84 commented on src/V2/OmsApi.php
> -        Extension $extension,
Это изменение ломает публичный интерфейс класса, лучше так не делать в стабильной версии библиотеки.

2020-10-06 09:14 UTC, XilefNori commented on src/V2/OmsApi.php
> -        Extension $extension,
Ломает. Мы увеличим мажорную версию.
Если посмотреть на исходный код, это изначально было странное решение.
У нас есть запрос (подкласс CreateOrderForEmissionICRequest) который однозначно определяет extension.
Указание extension лишнее.

2020-10-06 09:15 UTC, XilefNori commented on src/V2/Dto/CreateOrderForEmissionICRequestShoes.php
> +use DateTimeInterface;
Исправил. Спасибо.

2020-10-06 09:15 UTC, XilefNori commented on src/V2/Dto/CreateOrderForEmissionICRequestPerfum.php
> +use DateTimeInterface;
Исправил.

2020-10-06 09:15 UTC, XilefNori commented on src/V2/Dto/CreateOrderForEmissionICRequestLp.php
> +     * CreateOrderForEmissionICRequestLight constructor.
Исправил. Спасибо.

2020-10-06 09:15 UTC, XilefNori commented on src/V2/Dto/CreateOrderForEmissionICRequestLp.php
> +use DateTimeInterface;
Исправил

2020-10-06 09:34 UTC, toshksenof commented on src/V2/Dto/CreateOrderForEmissionICRequestLp.php
> +     * @param OrderProduct[] $products
Тут, пожалуй, подразумевается `OrderProductLp[]`

2020-10-06 09:58 UTC, XilefNori commented on src/V2/Dto/CreateOrderForEmissionICRequestLp.php
> +     * @param OrderProduct[] $products
OK

2020-10-06 15:55 UTC, HaiD84 approved these changes

2020-10-06 17:47 UTC, akurov-lam approved these changes

2020-10-08 12:46 UTC, merged